image:
  repository: thorvini/hello-world-war
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30150   # <- we choose 30081 because 30080 and 31174 are already in use
